@startuml Class Diagram
title Product Model
class Product{
    -name:string
    -price:float
    -quantity:int
    --
    +getname():string
    +getPrice():float
    +getQuantity():int
    --
    +setname(value:s tring)
    +setPrice(value:float)
    +setQuantity(value:int)
    --
    +Product(name:string, price:float, quantity:int)
    --
    +getTotalPrice():float
}

Product -up-|> Object : "<<Extends>>"

hide empty members

@enduml