@startuml
title Car Model
class Car{
    -manufacturer:string
    -Model:string
    -year:int
    +color:string
    +activeWipers(speed):void
    +openSunRoof():void
    +playRadio(station):void
    +drive():void
    +stop():void

}
@enduml